const router = require("express").Router();
const protect = require("../middleware/authMiddleware");
const controller = require("../controllers/transferController");
router.use(protect);
router.get("/", controller.getTransfers);
router.post("/", protect.allowRoles("student"), controller.createTransfer);
router.get("/:id/transcript", controller.downloadTranscript);
router.get("/:id", controller.getTransferById);
router.post("/:id/evaluate", protect.allowRoles("staff", "admin"), controller.evaluateTransfer);
router.put("/:id/review", protect.allowRoles("staff", "admin"), controller.reviewTransfer);
router.put("/:id/status", protect.allowRoles("admin"), controller.updateTransferStatus);
module.exports = router;
